-- Project requests from the public /start intake form.
-- Writes happen ONLY on the server (src/app/api/inquiry/route.ts) with the secret/service-role key,
-- which bypasses RLS. Browser roles (anon, authenticated) get no grants and no policies, so the public
-- publishable key can never read, insert, update, delete or enumerate rows.
-- Apply once: Supabase Dashboard > SQL Editor, or `supabase db push`. Safe to re-run.

create table if not exists public.project_requests (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  -- Idempotency key generated by the browser once per form session: a double click or a retry after a
  -- lost response can never create a second row.
  submission_key uuid not null unique,

  -- Contact
  client_name text not null check (char_length(client_name) between 1 and 120),
  email text not null check (char_length(email) between 3 and 254 and email like '%_@_%.__%'),
  phone text check (char_length(phone) <= 40),
  organization text check (char_length(organization) <= 120),

  -- Project
  package text not null check (package in ('launch', 'presence', 'business', 'custom')),
  website_type text check (char_length(website_type) <= 40),
  project_description text check (char_length(project_description) <= 4000),
  pages_needed jsonb check (pages_needed is null or jsonb_typeof(pages_needed) = 'array'),
  features_needed jsonb not null default '[]'::jsonb check (jsonb_typeof(features_needed) = 'array'),
  inspiration_links jsonb not null default '[]'::jsonb check (jsonb_typeof(inspiration_links) = 'array'),
  has_existing_website boolean,
  existing_website text check (char_length(existing_website) <= 500),
  domain_status text check (char_length(domain_status) <= 40),
  timeline text check (char_length(timeline) <= 40),
  budget text check (char_length(budget) <= 40),
  desired_launch_date date,

  -- Workflow (server-managed, never accepted from the browser)
  status text not null default 'new' check (status in (
    'new', 'contacted', 'awaiting_payment', 'paid', 'in_progress', 'awaiting_client', 'review', 'completed', 'cancelled'
  )),
  payment_status text not null default 'unpaid' check (payment_status in (
    'unpaid', 'pending', 'paid', 'partially_paid', 'refunded', 'failed'
  )),
  stripe_customer_id text,
  stripe_session_id text unique,
  amount_paid integer check (amount_paid >= 0), -- cents
  internal_notes text
);

comment on table public.project_requests is 'Website project requests from /start. Server-only access (service role); RLS denies all browser roles.';
comment on column public.project_requests.amount_paid is 'Amount paid in cents (Stripe convention).';
comment on column public.project_requests.timeline is 'Timing bucket chosen in the form (config/inquiry.ts timelines).';

create index if not exists project_requests_created_at_idx on public.project_requests (created_at desc);
create index if not exists project_requests_status_idx on public.project_requests (status);
create index if not exists project_requests_email_idx on public.project_requests (lower(email));

-- Keep updated_at current on every update.
create or replace function public.project_requests_touch_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists project_requests_touch_updated_at on public.project_requests;
create trigger project_requests_touch_updated_at
  before update on public.project_requests
  for each row execute function public.project_requests_touch_updated_at();

-- Security: RLS on with no policies = deny everything for anon/authenticated. Grants are revoked too,
-- so the table is invisible to the public Data API even if a policy is added by mistake later.
alter table public.project_requests enable row level security;
alter table public.project_requests force row level security;
revoke all on table public.project_requests from anon, authenticated;
revoke all on function public.project_requests_touch_updated_at() from anon, authenticated, public;
grant select, insert, update, delete on table public.project_requests to service_role;
